// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Comment struct {
	ID        string     `json:"id"`
	Username  string     `json:"username"`
	Text      string     `json:"text"`
	PostID    int        `json:"postID"`
	CommentID *int       `json:"commentID,omitempty"`
	Replies   []*Comment `json:"replies"`
}

type CommentInput struct {
	Username  string `json:"username"`
	Text      string `json:"text"`
	PostID    int    `json:"postID"`
	CommentID *int   `json:"commentID,omitempty"`
}

type Mutation struct {
}

type Post struct {
	ID          string     `json:"id"`
	Author      string     `json:"author"`
	Title       string     `json:"title"`
	Text        string     `json:"text"`
	IsCommented bool       `json:"isCommented"`
	Comments    []*Comment `json:"comments"`
}

type PostInput struct {
	Author      string `json:"author"`
	Title       string `json:"title"`
	Text        string `json:"text"`
	IsCommented bool   `json:"isCommented"`
}

type Query struct {
}
